- name: install dependencies
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - redis-server

- name: Set redis to listen to all interfaces
  lineinfile:
    name: /etc/redis/redis.conf
    regexp: '^bind.*'
    state: absent

- name: Set redis not to daemonize
  shell: sed -i 's/^\(daemonize\s*\)yes\s*$/\1no/g' /etc/redis/redis.conf

- name: Disable redis-server on boot and make sure it is stopped - supervisord takes care of this
  service:
    name: redis-server
    enabled: false
    state: stopped

- name: Create the Supervisor config file for redis
  template:
    src: etc/supervisor/conf.d/redis.conf.j2
    dest: /etc/supervisor/conf.d/redis.conf
    backup: yes

- name: Re-read the Supervisor config files
  command: supervisorctl reread

- name: Update Supervisor to add the app in the process group
  command: supervisorctl update

- name: Restart Supervisor
  command: supervisorctl restart redis
