---
- name: Create the Supervisor config file for Apache on www
  template: src=etc/supervisor/supervisor_config_apache.j2
            dest=/etc/supervisor/conf.d/{{ application_name }}-apache.conf
            backup=yes

- name: Create the Supervisor config file for www (devel)
  template: src=etc/supervisor/supervisor_config_devserver.j2
            dest=/etc/supervisor/conf.d/{{ application_name }}-application.conf
            backup=yes
  when: server_type == "devel"

- name: Create the Supervisor config file for www (prod)
  template: src=etc/supervisor/supervisor_config_gunicorn.j2
            dest=/etc/supervisor/conf.d/{{ application_name }}-application.conf
            backup=yes
  when: server_type == "prod"

- name: Create the Supervisor config file for Shibboleth on www
  template: src=etc/supervisor/supervisor_config_shibboleth.j2
            dest=/etc/supervisor/conf.d/{{ application_name }}-shibboleth.conf
            backup=yes
  when: enable_shibboleth

- name: Re-read the Supervisor config files
  command: supervisorctl reread

- name: Update Supervisor to add the app in the process group
  command: supervisorctl update
